-- Generated by https://roblox-ts.github.io v0.0.34
-- Compiled May 17, 2019, 7:38 PM Central Daylight Time

local _exports;
local ObjectStack;
do
	ObjectStack = {};
	ObjectStack.__index = {
		push = function(self, item)
			self.size = self.size + 1;
			item.previousNode = self.top;
			self.top = item;
		end;
		pop = function(self)
			local top = self.top;
			if top then
				self.size = self.size - 1;
				self.top = top.previousNode;
				return top;
			end;
		end;
		isEmpty = function(self)
			if self.top then
				return false;
			else
				return true;
			end;
		end;
		iterate = function(self)
			return {
				next = coroutine.wrap(function()
					do
						local current = self.top;
						while current do
							coroutine.yield({
								value = current;
								done = false;
							});
							current = current.previousNode;
						end;
					end;
					while true do coroutine.yield({ done = true }) end;
				end);
			};
		end;
	};
	ObjectStack.new = function(...)
		return ObjectStack.constructor(setmetatable({}, ObjectStack), ...);
	end;
	ObjectStack.constructor = function(self, ...)
		self.size = 0;
		return self;
	end;
end;
_exports = ObjectStack;
return _exports;
